### ISSUE TITLE
Feature 1: Business can create a profile

### ISSUE THREAD

**Issue by d-tak** [d-tak/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- Business can create a profile that contains
  - Name (arbitrary: filoKitchen)
  - Location (arbitrary: Irvine, CA)
  - Email (arbitrary: togetherisbetter@filoKitchen.eats)
  - Password (arbitrary: n/a)
  - Hours of Operation (arbitrary: M-F 11 AM to 10 PM / Saturdays 11 AM to 11 PM / Sundays Closed)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By creating a profile, Businesses will be able to post information pertaining to their establishment for prospective patrons who wish to place their names on a waitlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Wireframe - 1](https://user-images.githubusercontent.com/99932512/190003811-eff4e6e0-02b2-4f25-8f3c-338d1b5ef908.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to utilize code provided by dbdesigner.
- [x] Update `data.sql` to reflect arbitrary data for development phases.

### ☁️ Server Tasks

- [x] Update `server/index.js` to reflect conditions necessary to execute methods and queries for data entered into form fields.
  - [x] install all dependencies and devdependencies
  - [x] open communication path between client and server
  - [x] If 😉 middleware is activated then keep middleware running in the background (use)
  - [x] get information to fulfill necessary fields in form
  - [ ] query the database and send appropriate response to client.
- [x] Create middleware to communicate between database (server) and client.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create files for necessary HTML and CSS codes
- [x] Create an app.jsx file to handle data, mount, and render
- [x] Create a component for the header (HomePage: WaitingFuze)
- [x] Create a pages directory with one page (business profile creation)
- [x] Create page within pages directory - enter arbitrary data for app development.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
