### ISSUE TITLE
Feature 2: Business can view profile

### ISSUE THREAD

**Issue by d-tak** [d-tak/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- Business will be able to view its profile details entered on the previous page
  - Name
  - Location
  - Email
  - Hours 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When the business views its profile, it will be able to confirm what patrons see when making waitlist entries to the Waitlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to utilize code provided by dbdesigner for the BusinessProfile
- [x] Update `data.sql` to reflect data for development phases AND to reflect entries logged to database

### ☁️ Server Tasks

- [x] Add a GET route for retrieving a specific business profile at `/api/business/:businessId`
  - [x] (restaurant name, location, email, and hours) to populate within profile page.
- [x] Use SQL to query the database for a specific profile
- [x] Check communication path between client and server using httpie requests to ensure correct data is being accessed.
- [x] Respond with found business from the client to the server
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display business profile (named `ViewBusinessProfile`)
- [x] Update `app.jsx` file to render `ViewBusinessProfile` component when the hash route is `business` and pass the `businessId` from the hash route params (e.g. `?businessId=1`)
- [x] Update handleSubmit in `BusinessProfile` component to POST data to database **AND** automatically switch to profile view upon pressing confirm

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
