### ISSUE TITLE
Feature 6: Patron can join waitlist with name and mobile number

### ISSUE THREAD

**Issue by d-tak** [d-tak/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Patron can join waitlist with name and mobile number

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Patrons will be able to enter information into the form to post information relevant to their party and join the waitlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-16 at 10 51 48 AM](https://user-images.githubusercontent.com/99932512/190702684-1342f294-a057-4627-bc01-ccdacbfab3a8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to utilize code provided by dbdesigner for the waitlist
- [x] Update `data.sql` to reflect data for development phases

### ☁️ Server Tasks

- [x] Update `server/index.js` to to reflect conditions necessary to execute methods and queries for data entered into form fields.
  - [x] open communication path between client and server
  - [x] get information (restaurant name, location, email, and hours) to fulfill necessary fields in form
    - [x] insert data (sql) from previous business profile entry
  - [x] post data from client to server 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create files for necessary HTML and CSS Codes
- [x] update app.jsx file to handle data, mount, and render
- [x] Create a new file in the pages directory for the waitList
- [x] Create a component for the waitList

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
