### ISSUE TITLE
Feature 8: Patron can view waitlist

### ISSUE THREAD

**Issue by d-tak** [d-tak/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- Patron will be able to view existing Waitlist by clicking on blue button
 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
- Waitlist will display name and number in party in order input was received.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-22 at 11 16 10 AM](https://user-images.githubusercontent.com/99932512/191822397-637ddf4d-e37a-4c8d-9784-8f6017a2ace2.png)
![Screen Shot 2022-09-22 at 11 16 21 AM](https://user-images.githubusercontent.com/99932512/191822404-66abbe45-0204-4c90-9ba4-3f8ddc0b58f2.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update schema.sql to utilize code provided by dbdesigner for the BusinessProfile
- [x] Update data.sql to reflect data for development phases AND to reflect entries logged to database

### ☁️ Server Tasks

- [x] Add a GET route for retrieving data from the waitlist at /api/business/:businessId/patron-info/
  - [x] This should populate First Name of patron and number in party in order input was entered.
- [x] Use SQL to query the database for existing entries in waitList
- [x] Check communication path between client and server using httpie requests to ensure correct data is being accessed.
- [x] Respond with found data from client to the server
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display waitlist (named `ViewWaitList`)
- [x] Update `app.jsx` file to render `ViewWaitList` component when the hash route is `ViewWaitList` with appropriate `businessId`.
- [x] Use `this.props.businessId` when sending the patron to waitlist screen (fetch).
- [x] Update the window.location.hash in the WaitList component's submit handler when the fetch completes.
- [x] In `componentDidMount`, within the `WaitList` component mounts, (after form submission is completed - component -> render -> componentDidMount), INCLUDE `?businessID=` with the businessId from `this.props`.
- [x] Use form to SET the hash to switch screens to ViewWaitList
- [x] Create a button element to switch views when clicked
- [x] ViewWaitList will use the the businessId in its componentDidMount (linking the business and waitlists together)

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
